tunnel: 3ad6c97b-f82b-4fcf-912e-8596adc49da8
credentials-file: ~/.cloudflared/3ad6c97b-f82b-4fcf-912e-8596adc49da8.json

ingress:
  - hostname: vortfolio.icu
    service: http://localhost:8000
  - service: http_status:404
