services:
  wordpress:
    image: wordpress:latest
    container_name: wp_container
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000
      WORDPRESS_DB_NAME: vortfolio
      WORDPRESS_DB_USER: 3TJFdzBsW6BQcdA.root
      WORDPRESS_DB_PASSWORD: FcuHmsVgzsXf1Bwz
      WORDPRESS_DB_SSL: 1   # Enable SSL connection
      WORDPRESS_DB_SSL_CA: /certs/isrgrootx1.pem   # Path inside container
    volumes:
      - ./wordpress:/var/www/html
      - ./certs:/certs    # Mount folder containing isrgrootx1.pem
      
